version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: people_db
    restart: always
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  people-app:
    build: people-api/.
    container_name: people_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/people
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data:

